#!/usr/bin/env bash
set -euo pipefail

REPO_DIR=${REPO_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}
PARTITION=${PARTITION:-workq}
NNODES=${NNODES:-1}
N_GPUS_PER_NODE=${N_GPUS_PER_NODE:-4}
CPUS_PER_TASK=${CPUS_PER_TASK:-32}
MEM=${MEM:-120G}
TIME_LIMIT=${TIME_LIMIT:-04:00:00}
MODE=${MODE:-sync_colocate}
MODEL_SIZE=${MODEL_SIZE:-3b}
MODEL_PATH=${MODEL_PATH:-}
ENGINE=${ENGINE:-sglang}
VERL_DOCKER_ROOT=${VERL_DOCKER_ROOT:-$HOME/code/verl_docker}
SIF_PATH=${SIF_PATH:-$VERL_DOCKER_ROOT/verl_sgl056_arm64_latest.sif}
DATA_DIR=${DATA_DIR:-$HOME/data/geo3k}
HF_CACHE_DIR=${HF_CACHE_DIR:-$HOME/.cache/huggingface}
TRAIN_MAX_SAMPLES=${TRAIN_MAX_SAMPLES:-8}
VAL_MAX_SAMPLES=${VAL_MAX_SAMPLES:-4}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-4}
GEN_BATCH_SIZE=${GEN_BATCH_SIZE:-1}
N_RESP_PER_PROMPT=${N_RESP_PER_PROMPT:-1}
TOTAL_EPOCHS=${TOTAL_EPOCHS:-1}
PROFILE_STEPS=${PROFILE_STEPS:-[1]}
GLOBAL_PROFILER_TOOL=${GLOBAL_PROFILER_TOOL:-torch}
LOCALIZE_MODEL_FROM_HF=${LOCALIZE_MODEL_FROM_HF:-1}
TRAINER_N_GPUS_PER_NODE=${TRAINER_N_GPUS_PER_NODE:-2}
ROLLOUT_N_GPUS_PER_NODE=${ROLLOUT_N_GPUS_PER_NODE:-2}
RUN_NAME=${RUN_NAME:-${MODE}_${MODEL_SIZE}_${ENGINE}_$(date +%Y%m%d_%H%M%S)}

mkdir -p "$REPO_DIR/runs/multimodality/slurm_logs"
JOB_SCRIPT=$(mktemp "$REPO_DIR/runs/multimodality/slurm_logs/${MODE}_${MODEL_SIZE}_${ENGINE}_XXXXXX.slurm")
cat > "$JOB_SCRIPT" <<EOF
#!/usr/bin/env bash
#SBATCH -J mm_${MODE}_${MODEL_SIZE}_${ENGINE}
#SBATCH -p ${PARTITION}
#SBATCH -N ${NNODES}
#SBATCH --ntasks=1
#SBATCH --gres=gpu:${N_GPUS_PER_NODE}
#SBATCH --cpus-per-task=${CPUS_PER_TASK}
#SBATCH --mem=${MEM}
#SBATCH -t ${TIME_LIMIT}
#SBATCH -o ${REPO_DIR}/runs/multimodality/slurm_logs/%x_%j.out
#SBATCH -e ${REPO_DIR}/runs/multimodality/slurm_logs/%x_%j.err
set -euo pipefail
module load cuda/12.6 nvidia/24.11
cd ${REPO_DIR}
export MODE=${MODE}
export MODEL_SIZE=${MODEL_SIZE}
export ENGINE=${ENGINE}
export MODEL_PATH=${MODEL_PATH}
export NNODES=${NNODES}
export N_GPUS_PER_NODE=${N_GPUS_PER_NODE}
export TRAINER_N_GPUS_PER_NODE=${TRAINER_N_GPUS_PER_NODE}
export ROLLOUT_N_GPUS_PER_NODE=${ROLLOUT_N_GPUS_PER_NODE}
export TRAIN_MAX_SAMPLES=${TRAIN_MAX_SAMPLES}
export VAL_MAX_SAMPLES=${VAL_MAX_SAMPLES}
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE}
export GEN_BATCH_SIZE=${GEN_BATCH_SIZE}
export N_RESP_PER_PROMPT=${N_RESP_PER_PROMPT}
export TOTAL_EPOCHS=${TOTAL_EPOCHS}
export PROFILE_STEPS='${PROFILE_STEPS}'
export GLOBAL_PROFILER_TOOL=${GLOBAL_PROFILER_TOOL}
export LOCALIZE_MODEL_FROM_HF=${LOCALIZE_MODEL_FROM_HF}
export RUN_NAME=${RUN_NAME}
export VERL_DOCKER_ROOT=${VERL_DOCKER_ROOT}
export SIF_PATH=${SIF_PATH}
export DATA_DIR=${DATA_DIR}
export HF_CACHE_DIR=${HF_CACHE_DIR}
export HYDRA_FULL_ERROR=1
export RAY_DEDUP_LOGS=0
export SGLANG_DISABLE_TP_MEMORY_INBALANCE_CHECK=True
bash scripts/multimodality/run_profiled_grpo_vlm_apptainer.sh
EOF
chmod +x "$JOB_SCRIPT"
echo "$JOB_SCRIPT"
sbatch --wait "$JOB_SCRIPT"
